#include "pack.hpp"

#include "handlers/cruds.pb.h"
#include "string_to_uuid.hpp"

#include <userver/formats/json/serialize.hpp>

namespace Utils {

auto GetPackFromRequest(const userver::server::http::HttpRequest& request)
    -> Models::Pack {
    const auto& body =
        userver::formats::json::FromString(request.RequestBody());
    return Models::Pack{
        .id = {}, // Will be generated by database
        .title = body["title"].As<std::string>(),
    };
}

Models::Pack::PackId
GetPackIdFromRequest(const userver::server::http::HttpRequest& request) {
    const auto& body = request.RequestBody();
    auto json = userver::formats::json::FromString(body);

    auto pack_id_str = json["pack_id"].As<std::string>();
    return Utils::StringToUuid(pack_id_str);
}

auto GetPackFromRequest(handlers::api::CreatePackRequest&& request)
    -> std::expected<Models::Pack, grpc::Status> {
    if (request.title().empty()) {
        return std::unexpected(
            grpc::Status{
                grpc::StatusCode::INVALID_ARGUMENT, "Pack title cannot be empty"
            }
        );
    }
    return Models::Pack{
        .id = {}, // Will be generated by database
        .title = request.title(),
    };
}

} // namespace Utils
