#include "question.hpp"

#include "handlers/cruds.pb.h"
#include "string_to_uuid.hpp"

#include <userver/formats/json/serialize.hpp>
#include <userver/formats/parse/common_containers.hpp>

namespace Utils {

auto GetQuestionFromRequest(const userver::server::http::HttpRequest& request)
    -> Models::Question {
    const auto& body =
        userver::formats::json::FromString(request.RequestBody());
    return Models::Question{
        .id = {},                           // Will be generated by database
        .pack_id = Utils::StringToUuid(""), // Will be set in handler from path
        .text = body["text"].As<std::string>(),
        .image_url =
            body["image_url"].As<std::optional<std::string>>().value_or(""),
        .question_type = body["question_type"]
                             .As<std::optional<Models::QuestionType>>()
                             .value_or(Models::QuestionType::kMultipleChoice),
    };
}

auto GetQuestionFromRequest(handlers::api::CreateQuestionRequest&& request)
    -> std::expected<Models::Question, grpc::Status> {
    if (request.text().empty()) {
        return std::unexpected(
            grpc::Status{
                grpc::StatusCode::INVALID_ARGUMENT,
                "Question text cannot be empty"
            }
        );
    }
    const auto pack_id = Utils::StringToUuid(request.pack_id());
    if (pack_id.is_nil()) {
        return std::unexpected(
            grpc::Status{
                grpc::StatusCode::INVALID_ARGUMENT,
                "Invalid UUID format: " + request.pack_id()
            }
        );
    }

    auto question_type = Models::QuestionType::kMultipleChoice;
    const auto& qt_str = request.question_type();
    if (qt_str == "free_text") {
        question_type = Models::QuestionType::kFreeText;
    } else if (qt_str == "custom") {
        question_type = Models::QuestionType::kCustom;
    } else if (!qt_str.empty() && qt_str != "multiple_choice") {
        return std::unexpected(
            grpc::Status{
                grpc::StatusCode::INVALID_ARGUMENT,
                "Invalid question_type: " + qt_str
            }
        );
    }

    return Models::Question{
        .id = {}, // Will be generated by database
        .pack_id = Utils::StringToUuid(request.pack_id()),
        .text = request.text(),
        .image_url = request.image_url(),
        .question_type = question_type,
    };
}

} // namespace Utils
