#include "variant.hpp"

#include "handlers/cruds.pb.h"
#include "string_to_uuid.hpp"

#include <userver/formats/json/serialize.hpp>

namespace Utils {

Models::Variant
GetVariantFromRequest(const userver::server::http::HttpRequest& request) {
    const auto& question_id_str = request.GetPathArg("question_id");
    const auto& body =
        userver::formats::json::FromString(request.RequestBody());
    return Models::Variant{
        .id = {}, // Will be generated by database
        .question_id = Utils::StringToUuid(question_id_str),
        .text = body["text"].As<std::string>(),
        .is_correct = body["is_correct"].As<bool>(false),
    };
}

auto GetVariantFromRequest(handlers::api::CreateVariantRequest&& request)
    -> std::expected<Models::Variant, grpc::Status> {
    if (request.text().empty()) {
        return std::unexpected(
            grpc::Status{
                grpc::StatusCode::INVALID_ARGUMENT,
                "Variant text cannot be empty"
            }
        );
    }
    const auto question_id = Utils::StringToUuid(request.question_id());
    if (question_id.is_nil()) {
        return std::unexpected(
            grpc::Status{
                grpc::StatusCode::INVALID_ARGUMENT,
                "Invalid UUID format: " + request.question_id()
            }
        );
    }
    return Models::Variant{
        .id = {}, // Will be generated by database
        .question_id = Utils::StringToUuid(request.question_id()),
        .text = request.text(),
        .is_correct = request.is_correct(),
    };
}

} // namespace Utils
